/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author carlosafc
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroClientes = new javax.swing.JMenuItem();
        menuCadastroEquipamentos = new javax.swing.JMenuItem();
        menuSair1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina Ilhatec");
        setPreferredSize(new java.awt.Dimension(600, 450));

        desktopPane.setBackground(new java.awt.Color(102, 102, 255));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(640, 4));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        desktopPane.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 600, 460);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_arquivo_16x16.png"))); // NOI18N
        menuCadastro.setMnemonic('f');
        menuCadastro.setText("Cadastros e Consultas");

        menuCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_cliente_16x16.png"))); // NOI18N
        menuCadastroClientes.setMnemonic('c');
        menuCadastroClientes.setText("Clientes");
        menuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroClientes);

        menuCadastroEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_equipamento_16x16.png"))); // NOI18N
        menuCadastroEquipamentos.setMnemonic('e');
        menuCadastroEquipamentos.setText("Equipamentos");
        menuCadastroEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroEquipamentosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroEquipamentos);

        menuSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_sair_16x16.png"))); // NOI18N
        menuSair1.setText("Sair");
        menuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair1ActionPerformed(evt);
            }
        });
        menuCadastro.add(menuSair1);

        menuBar.add(menuCadastro);

        setJMenuBar(menuBar);

        getAccessibleContext().setAccessibleName("Ordem de Serviço");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClientesActionPerformed
        // TODO add your handling code here:
        ClienteView cadCliente = new ClienteView();
        jDesktopPane1.add(cadCliente);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_menuCadastroClientesActionPerformed

    private void menuCadastroEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroEquipamentosActionPerformed
        // TODO add your handling code here:
        EquipamentoView cadEquipamento = new EquipamentoView();
        this.desktopPane.add(cadEquipamento);
        cadEquipamento.setVisible(true);
    }//GEN-LAST:event_menuCadastroEquipamentosActionPerformed


    private void menuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair1ActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza?", "Atenção", JOptionPane.YES_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroClientes;
    private javax.swing.JMenuItem menuCadastroEquipamentos;
    private javax.swing.JMenuItem menuSair1;
    // End of variables declaration//GEN-END:variables

}
